name: Release Action-vnext

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: debug
        run: |
          ls -la .git
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image and load it locally.
      - name: Build Docker image (latest tag)
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: action-vnext:latest

      # Use docker compose to run the vnext service and compute the version.
      - name: Compute Version Using docker compose
        id: compute-version
        run: |
          # Run the vnext service via docker compose to mount the current repo.
          docker compose run -e LOG_LEVEL=debug --rm vnext
          VERSION=$(docker compose run --rm vnext)
          echo "Computed version: $VERSION"
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      # Create a Git tag using the computed version and push it.
      - name: Create and Push Git Tag
        run: |
          git tag "${{ steps.compute-version.outputs.version }}"
          git push --tags

      # Build and push the Docker image with the computed version tag to GHCR.
      - name: Build and Push Docker Image with Version Tag
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.compute-version.outputs.version }}

      # Create a GitHub Release with the computed version tag.
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.compute-version.outputs.version }}
